#!/bin/bash -l

#$ -P rcstest
# This should be running for the entire duration
# of the tests. This can be reduced on the qsub
# command line if you want.
#$ -l h_rt=48:00:00
#$ -N nf_pkgtest
#$ -m eas

module load nextflow
module use /share/module.8/rcstools
module load pkgautotest/1.0

nextflow $PKGTEST_SCRIPT --csv_input $1
